### ISSUE TITLE
Clarification on which directions XY and Z points are in pointcloud, is it using unified normative coordinate system?

### ISSUE THREAD

**Issue by SaMeEr9597** [eduardohenriquearnold/CODD#2]
Hi,
Does the point cloud use the unified normative coordinate system (hat is, x-axis points towards to front direction, y-axis points towards to the left direction, and z-axis points towards to the top direction.), or is it using another coordinate system ? 
Thanks

**Comment by eduardohenriquearnold** [comment]
The point clouds use the CARLA (Unreal Engine) coordinate system where (x-forward, y-right, z-up). Also, note that the point clouds are in the local (sensor) coordinate frame.
